templates.createStudentViewTpl = _.template([
    '<section class="modal-window modal_singleStudent">',
        '<section class="dropZone form-inline form-wrapper container">',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Group name</label>',
                    '<input name = "groupId" value = "<%= name %>" class = "form-control" disabled>',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Incoming test</label>',
                    '<input name = "incomingTest" class = "form-control">',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 firstNameInput">',
                    '<label class = "control-label">First name</label>',
                    '<input name = "FirstName" class = "form-control firstName">',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 firstNameInput">',
                    '<label class = "control-label">Entry score</label>',
                    '<input name = "entryScore" class = "form-control" maxlength="3" placeholder="For example 3.5">',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Last name</label>',
                    '<input name = "LastName" class = "form-control lastName">',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Approved by</label>',
                    '<select class = "form-control approvedBy">',
                      '<option value="Not approved">Not approved</option>',
                      '<% if (experts.length > 0) { %>',
                        '<% _.each(experts, function(expert) { %>',  
                            '<option value="<%= expert %>"><%= expert %></option>',
                        '<% }); %>',
                      '<% } %>',
                      '<option value=Custom>Custom</option>',
                    '</select>',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">English level</label>',
                    '<select class = "form-control englishLevel">',
                      '<option value="Elementary">Elementary</option>',
                      '<option value="Pre-intermediate low">Pre-intermediate low</option>',
                      '<option value="Pre-intermediate">Pre-intermediate</option>',
                      '<option value="Pre-intermediate strong">Pre-intermediate strong</option>',
                      '<option value="Intermediate low">Intermediate low</option>',
                      '<option value="Intermediate">Intermediate</option>',
                      '<option value="Intermediate strong">Intermediate strong</option>',
                      '<option value="Upper-intermediate low">Upper-intermediate low</option>',
                      '<option value="Upper-intermediate">Upper-intermediate</option>',
                      '<option value="Upper-intermediate strong">Upper-intermediate strong</option>',
                      '<option value="Advanced">Advanced</option>',
                    '</select>',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label custom-approval"></label>',
                    '<input name = "CustomApproval" class = "hidden form-control custom-approval-input" disabled>',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">CV</label>',
                        '<ul class = "downloadedCV">',
                        '</ul>',
                        '<button class = "BrowseCV form-control btn btn-default active">Browse</button>',
                        '<input name="uploadCV" type="file" class="hidden" accept="application/msword,application/pdf,application/rtf,.docx">',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Photo</label>',
                        '<ul class = "downloadedPhoto">',
                        '</ul>',
                        '<button class = "BrowsePhoto form-control btn btn-default active">Browse</button>',
                        '<input name="uploadPhoto" type="file" class="hidden" accept="image/jpeg,image/jpg,image/png,image/tiff">',
                '</div>',
            '</div>',

            '<div class = "buttons">',
                '<button class = "save-changes fa fa-check-circle-o fa-3x btn-icon"></button>',
                '<button class = "close-modal-window fa fa-times-circle-o fa-3x btn-icon"></button>',
            '</div>',

        '</section>',
    '</section>',
].join(''));

templates.studentDownloadedPhotoTpl = _.template([
    '<li>',
    '    <span class="list-item"><%= name %></span>',
    '    <span class="remove-photo fa fa-times-circle-o fa-2x small-btn" data-photo="<%= name %>"</span>',
    '</li>',
].join(''));

templates.studentDownloadedCVTpl = _.template([
    '<li>',
    '    <span class="list-item"><%= name %></span>',
    '    <span class="remove-cv fa fa-times-circle-o fa-2x small-btn" data-cv="<%= name %>"</span>',
    '</li>',
].join(''));