templates.oneStudentViewTpl = _.template([
    '<tr>',
        '<% if (name === "empty") { %>',
            '<td name="studName"></td>',
        '<% } else { %>',
            '<td name="studName"><%= lastName %> <%= name %></td>',
        '<% } %>',
        '<% if (avatar === "empty") { %>',
            '<td></td>',
        '<% } else if (avatar) { %>',
            '<td><%= avatar %></td>',
        '<% } else { %>',
            '<td><img class="photo img-circle" src="/img/default-photo.png"/></td>',
        '<% } %>',
        '<% if (englishLevel === "empty") { %>',
            '<td></td>',
        '<% } else { %>',
            '<td><%= englishLevel %></td>',
        '<% } %>',
        '<% if (incomingScore === "empty") { %>',
            '<td></td>',
        '<% } else { %>',
            '<td><%= incomingScore %></td>',
        '<% } %>',
        '<% if (entryScore === "empty") { %>',
            '<td></td>',
        '<% } else { %>',
            '<td><%= entryScore %></td>',
        '<% } %>',
        '<% if (approvedBy === "empty") { %>',
            '<td></td>',
        '<% } else { %>',
            '<td class="approvedBy"><%= approvedBy %></td>',
        '<% } %>',
    '</tr>'
].join(''));