'use strict';
templates.resourceViewTpl = _.template([
    '<ul class="column-resource">',
        '<li class="form-group teacher-wrapper col-xs-12">',
            '<select class="form-control" name="resourceteacher" tabindex="1">',
                '<% _(teachers).each(function(teacher) { %>',
                '<option data-name="teacher" value="<%= teacher %>" <%= teacher === defaultTeacher ? \'selected\' : \'\' %> > <%= teacher %> </option>',
                '<% }); %>',
            '</select>',
        '</li>',
        '<li class="form-group room-wrapper col-xs-12">',
            '<select class="form-control" name="room" tabindex="2">',
                '<% _(rooms).each(function(room) { %>',
                '<option data-name="room" value="<%= room %>" <%= room === defaultRoom ? \'selected\' : \'\' %> > <%= room %> </option>',
                '<% }); %>',
            '</select>',
        '</li>',
        '<li class="form-group event-wrapper col-xs-12">',
            '<select class="form-control" name="event" tabindex="3">',
                '<option data-name="event" value="Regular">Regular</option>',
                '<option data-name="event" value="Special">Special</option>',
            '</select>',
        '</li>',                            
    '</ul>',
].join(''));