templates.scheduleViewTpl = _.template([
    '<div class="Table">',
        '<div class="Title"></div>',
        '<div class="Heading">',
            '<div class="Cell null"></div>',
            '<div class="Cell monday">Monday</div>',
            '<div class="Cell tuesday">Tuesday</div>',
            '<div class="Cell wednesday">Wednesday</div>',
            '<div class="Cell thursday">Thursday</div>',
            '<div class="Cell friday">Friday</div>',
        '</div>',
        '<div class="Row nine">',
            '<div class="HeadingCell">9:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row nine-half">',
            '<div class="HeadingCell">9:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row ten">',
            '<div class="HeadingCell">10:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row ten-half">',
            '<div class="HeadingCell">10:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row eleven">',
            '<div class="HeadingCell">11:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row eleven-half">',
            '<div class="HeadingCell">11:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row twelve">',
            '<div class="HeadingCell">12:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row twelve-half">',
            '<div class="HeadingCell">12:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row thirteen">',
            '<div class="HeadingCell">13:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row thirteen-half">',
            '<div class="HeadingCell">13:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row fourteen">',
            '<div class="HeadingCell">14:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row fourteen-half">',
            '<div class="HeadingCell">14:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row fifteen">',
            '<div class="HeadingCell">15:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row fifteen-half">',
            '<div class="HeadingCell">15:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row sixteen">',
            '<div class="HeadingCell">16:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row sixteen-half">',
            '<div class="HeadingCell">16:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row seventeen">',
            '<div class="HeadingCell">17:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row seventeen-half">',
            '<div class="HeadingCell">17:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row eighteen">',
            '<div class="HeadingCell">18:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row eighteen-half">',
            '<div class="HeadingCell">18:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row nineteen">',
            '<div class="HeadingCell">19:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row nineteen-half">',
            '<div class="HeadingCell">19:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row twenty">',
            '<div class="HeadingCell">20:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row twenty-half">',
            '<div class="HeadingCell">20:30</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
        '<div class="Row twenty-one">',
            '<div class="HeadingCell">21:00</div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
            '<div class="Cell"></div>',
        '</div>',
    '</div>'
].join(''));